### PR TITLE
Enable property config file usage

### LINKED ISSUE #31: [FEATURE REQUEST] Support for loading Genesis config from `.properties` files
**Is your feature request related to a problem? Please describe.**

I want it to be easy to edit and maintain the configuration outside of the Unity editor, because I manage the process of code generation almost exclusively outside of the editor. JSON works, but its inability to use newlines means it's an enormous pain in the ass to configure properties that need to extend past one line.

**Describe the solution you'd like**

The ability to load Genesis config from `.properties` files, just like legacy Entitas supports.

**Describe alternatives you've considered**

Managing my Genesis config in the editor. However, that means I'd have to implement a custom drawer for each config item I implement. Also, if my code doesn't compile then I can't *use* these custom drawers.

### PR DESCRIPTION
**Pull request by JesseTG**
# Description

This PR allows Genesis configuration to be loaded on the command line as a `.properties` file. To use this feature, load a config file whose file extension is `.properties`. It does not affect loading from base64-encoded config; that still has to be JSON.

I implemented this to simplify the management of Genesis config outside of Unity. I didn't want to keep screwing around with JSON that clearly wasn't intended to be human-editable.

Fixes #31

# How Has This Been Tested?

I transcribed my JSON configuration for Genesis into a `.properties` file and then ran Genesis. It worked like a charm.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by jeffcampbellmakesgames** [comment]
@JesseTG Do you have an example of a properties file I can test with? I'd also use one as an example for the wiki as well

**Comment by JesseTG** [comment]
Sure, here's one directly from my project:

```properties
Genesis.DoUseWhiteListedAssemblies = false
Genesis.WhiteListedAssemblies = Assembly-CSharp, Assembly-CSharp-Editor
Genesis.SearchPaths = Plugins

Genesis.Plugins = \
  CorundumGames.Codegen.Redux.Plugins, \
  EntitasRedux.Core.Plugins, \
  EntitasRedux.Unity.Blueprint.Plugins, \
  EntitasRedux.Unity.VisualDebugging.Plugins, \
  Genesis.Core.Plugin, \
  Genesis.Unity.Factory.Plugin

Genesis.PreProcessors =

Genesis.DataProviders = \
  CorundumGames.Codegen.Redux.Plugins.DisposableComponent.DisposableComponentDataProvider, \
  CorundumGames.Codegen.Redux.Plugins.GameObjectComponent.GameObjectComponentDataProvider, \
  CorundumGames.Codegen.Redux.Plugins.IndexByEnum.IndexByEnumDataProvider, \
  CorundumGames.Codegen.Redux.Plugins.InitFromUnityComponent.InitFromUnityComponentDataProvider, \
  EntitasRedux.Core.Plugins.ComponentDataProvider, \
  EntitasRedux.Core.Plugins.ContextDataProvider, \
  EntitasRedux.Core.Plugins.EntityIndexDataProvider, \
  Genesis.Unity.Factory.Plugin.ScriptableFactoryDataProvider

Genesis.CodeGenerators = \
  CorundumGames.Codegen.Redux.Plugins.PostProcessors.LogCodeGeneratorData, \
  CorundumGames.Codegen.Redux.Plugins.Context.DisposableContextGenerator, \
  CorundumGames.Codegen.Redux.Plugins.DisposableComponent.DisposableComponentGenerator, \
  CorundumGames.Codegen.Redux.Plugins.EntityBehaviour.EntityBehaviourGenerator, \
  CorundumGames.Codegen.Redux.Plugins.IndexByEnum.IndexByEnumGenerator, \
  CorundumGames.Codegen.Redux.Plugins.InitFromUnityComponent.InitFromUnityComponentGenerator, \
  CorundumGames.Codegen.Redux.Plugins.Context.AttributeGenerator, \
  CorundumGames.Codegen.Redux.Plugins.Context.TypeEnumGenerator, \
  EntitasRedux.Core.Plugins.CleanupDestroyEntitySystemGenerator, \
  EntitasRedux.Core.Plugins.CleanupRemoveComponentSystemGenerator, \
  EntitasRedux.Core.Plugins.ComponentContextApiGenerator, \
  EntitasRedux.Core.Plugins.ComponentEntityApiGenerator, \
  EntitasRedux.Core.Plugins.ComponentEntityApiInterfaceGenerator, \
  EntitasRedux.Core.Plugins.ComponentGenerator, \
  EntitasRedux.Core.Plugins.ComponentLookupGenerator, \
  EntitasRedux.Core.Plugins.ComponentMatcherApiGenerator, \
  EntitasRedux.Core.Plugins.ContextAttributeGenerator, \
  EntitasRedux.Core.Plugins.ContextCleanupFeatureGenerator, \
  EntitasRedux.Core.Plugins.ContextCleanupSystemsGenerator, \
  EntitasRedux.Core.Plugins.ContextGenerator, \
  EntitasRedux.Core.Plugins.ContextMatcherGenerator, \
  EntitasRedux.Core.Plugins.ContextsGenerator, \
  EntitasRedux.Core.Plugins.EntityGenerator, \
  EntitasRedux.Core.Plugins.EntityIndexGenerator, \
  EntitasRedux.Core.Plugins.EventEntityApiGenerator, \
  EntitasRedux.Core.Plugins.EventListenerComponentGenerator, \
  EntitasRedux.Core.Plugins.EventListenerInterfaceGenerator, \
  EntitasRedux.Core.Plugins.EventSystemGenerator, \
  EntitasRedux.Core.Plugins.EventSystemsGenerator, \
  EntitasRedux.Unity.BlueprintPlugins.BlueprintClassGenerator,\
  EntitasRedux.Unity.VisualDebuggingPlugins.ContextObserverGenerator, \
  EntitasRedux.Unity.VisualDebuggingPlugins.FeatureClassGenerator, \
  Genesis.Unity.Factory.Plugin.ScriptableFactoryCodeGenerator

Genesis.PostProcessors = \
  Genesis.Core.Plugin.AddFileHeaderPostProcessor, \
  Genesis.Core.Plugin.CleanTargetDirectoryPostProcessor, \
  Genesis.Core.Plugin.NewLinePostProcessor, \
  Genesis.Core.Plugin.MergeFilesPostProcessor, \
  Genesis.Core.Plugin.WriteToDiskPostProcessor

Genesis.TargetDirectory = Assets/Scripts/Generated

EntitasRedux.CodeGeneration.Plugins.Contexts = \
  Game, \
  Engine, \
  Global, \
  Timer, \
  Ui, \
  Status

CorundumGames.Codegen.Redux.Plugins.GameObjectComponent.Contexts = Game, Global, Ui

EntitasRedux.CodeGeneration.Plugins.Templates = Plugins/EntitasRedux/Templates
Genesis.LineEndings = Unix
```

**Comment by jeffcampbellmakesgames** [comment]
I've merged this code in with some slight changes. Something I have tried to make easy with this framework is the ability to generate the config content so a human being would not need to make it from scratch (noting all of the absolute namespaths to each plugin, looking up the possible config params, etc....). I've grabbed the PR branch and updated the `config` verb so that a developer can optionally generate a properties file as well as an alternative to a json config. This has been merged and published with `2.4.6`.

**CLI Command**
`dotnet .\Genesis.CLI.dll config --use-properties-file`

**Output Properties File contents**
```properties
Genesis.DoUseWhiteListedAssemblies=false
Genesis.WhiteListedAssemblies= /
    Assembly-CSharp /
    Assembly-CSharp-Editor /
Genesis.SearchPaths=Plugins
Genesis.Plugins= /
    Genesis.Core.Plugin /
    Genesis.Unity.Factory.Plugin /
Genesis.PreProcessors=
Genesis.DataProviders=Genesis.Unity.Factory.Plugin.ScriptableFactoryDataProvider
Genesis.CodeGenerators=Genesis.Unity.Factory.Plugin.ScriptableFactoryCodeGenerator
Genesis.PostProcessors= /
    Genesis.Core.Plugin.AddFileHeaderPostProcessor /
    Genesis.Core.Plugin.CleanTargetDirectoryPostProcessor /
    Genesis.Core.Plugin.NewLinePostProcessor /
    Genesis.Core.Plugin.MergeFilesPostProcessor /
    Genesis.Core.Plugin.WriteToDiskPostProcessor /
Genesis.AllPreProcessors=
Genesis.AllDataProviders=Genesis.Unity.Factory.Plugin.ScriptableFactoryDataProvider
Genesis.AllCodeGenerators=Genesis.Unity.Factory.Plugin.ScriptableFactoryCodeGenerator
Genesis.AllPostProcessors= /
    Genesis.Core.Plugin.AddFileHeaderPostProcessor /
    Genesis.Core.Plugin.CleanTargetDirectoryPostProcessor /
    Genesis.Core.Plugin.NewLinePostProcessor /
    Genesis.Core.Plugin.MergeFilesPostProcessor /
    Genesis.Core.Plugin.WriteToDiskPostProcessor /
Genesis.TargetDirectory=Assets
Genesis.LineEndings=Unix
```

**Comment by JesseTG** [comment]
Thank you very much!

**Pull request closed without merging**
